version: '3.8'


services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
# docker-compose.yaml
# This file defines the services and networks for the application.  
